[settings]
experimental = true
lockfile = true

############################################################################
# Tools Configuration                                                      #
############################################################################

[tools]

# ==========================================================================
# Compilers
# ==========================================================================

# TODO: add here any build tool you may need (e.g. cmake, make, ninja, etc.)

# ==========================================================================
# Languages & Runtimes (alphabetically sorted)
# ==========================================================================

# Node.js for jscpd & eslint
#
[tools.node]
version = "latest"

# Python and package manager
#
[tools.python]
version = "3.11" # Will install 3.11 or above based on availability

[tools.uv]
version = "latest"

# ==========================================================================
# CLI Tools (alphabetically sorted by tool name)
# ==========================================================================

# TODO: add here any build tool dependencies you may need that you cannot add
# to a config file (e.g. cargo:cargo-audit, npm:jscpd, etc.)
